### ISSUE TITLE
Possible to add selectionMode in the xml to the widget?

### ISSUE THREAD

**Issue by ghost** [gantonious/MaterialDayPicker#50]
I'm not seeing anything that lets me set the selectionMode in the layout file, only programmatically. Also, there's setOnDayPressedListener where I can pass *this* by implementing the OnDayPressedListener interface in my activity/fragment. Should be easy to add both, make my code look 3% nicer :D, thanks for the library btw.

**Comment by gantonious** [comment]
As for setting the `selectionMode` in XML that should be doable to implement. We can support setting selection modes that have empty constructors via xml.

> Also, there's setOnDayPressedListener where I can pass this by implementing the OnDayPressedListener interface in my activity/fragment.

This is should be possible in Java. In Kotlin however `setOnDayPressedListener` takes in a lambda expression instead of the `OnDayPressedListener` interface. If you want to set the interface explicitly you'll need to do it via the dayPressedListener property:


```kotlin
materialDayPicker.dayPressedListener = this
```

**Comment by ghost** [comment]
Ok let me know when you get it done.

**Comment by gantonious** [comment]
You can now define the selection mode via xml using the latest version:

```groovy
dependencies {
    implementation 'ca.antonious:materialdaypicker:0.7.0'
}
```
